export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const CUSTOMER_LOADED = 'CUSTOMER_LOADED';
export const CREATE_NEW_CUSTOMER_SUCCESS = 'CREATE_NEW_CUSTOMER_SUCCESS';
export const CREATE_NEW_CUSTOMER_FAIL = 'CREATE_NEW_CUSTOMER_FAIL';
export const EDIT_CUSTOMER_SUCCESS ='EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAIL ='EDIT_CUSTOMER_FAIL';
export const DELETE_CUSTOMER_SUCCESS ='DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL ='DELETE_CUSTOMER_FAIL';

export const MORTAGE_LOADING = 'MORTAGE_LOADING';
export const MORTAGE_LOADED = 'MORTAGE_LOADED';
export const MORTAGE_LOADING_ERROR = 'MORTAGE_LOADING_ERROR';
export const CREATE_NEW_MORTAGE_SUCCESS = 'CREATE_NEW_MORTAGE_SUCCESS';
export const CREATE_NEW_MORTAGE_FAIL = 'CREATE_NEW_MORTAGE_FAIL';
export const DELETE_MORTAGE = 'DELETE_MORTAGE';
export const CHANGE_STATUS_OF_MORTAGE = 'CHANGE_STATUS_OF_MORTAGE';
export const EDIT_MORTAGE_SUCCESS ='EDIT_MORTAGE_SUCCESS';
export const EDIT_MORTAGE_FAIL ='EDIT_MORTAGE_FAIL';

export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const PAYMENT_LOADED = 'PAYMENT_LOADED';
export const PAYMENT_LOADING_ERROR = 'PAYMENT_LOADING_ERROR';
export const CREATE_NEW_PAYMENT_SUCCESS = 'CREATE_NEW_PAYMENT_SUCCESS';
export const CREATE_NEW_PAYMENT_FAIL = 'CREATE_NEW_PAYMENT_FAIL';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';