export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_ERROR = 'USER_ERROR';
export const CREATE_NEW_CUSTOMER_SUCCESS = 'CREATE_NEW_CUSTOMER_SUCCESS';
export const CREATE_NEW_CUSTOMER_FAIL = 'CREATE_NEW_CUSTOMER_FAIL';

export const MORTAGE_LOADING = 'MORTAGE_LOADING';
export const MORTAGE_LOADED = 'MORTAGE_LOADED';
export const MORTAGE_LOADING_ERROR = 'MORTAGE_LOADING_ERROR';
export const CREATE_NEW_MORTAGE_SUCCESS = 'CREATE_NEW_MORTAGE_SUCCESS';
export const CREATE_NEW_MORTAGE_FAIL = 'CREATE_NEW_MORTAGE_FAIL';
export const DELETE_MORTAGE = 'DELETE_MORTAGE';

export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const PAYMENT_LOADED = 'PAYMENT_LOADED';
export const PAYMENT_LOADING_ERROR = 'PAYMENT_LOADING_ERROR';
export const CREATE_NEW_PAYMENT_SUCCESS = 'CREATE_NEW_PAYMENT_SUCCESS';
export const CREATE_NEW_PAYMENT_FAIL = 'CREATE_NEW_PAYMENT_FAIL';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';